version: "3"

services: 
  app:
    build: .
    command: yarn dev
    ports: 
      - "3333:3000"
    volumes: 
      - .:/usr/app
    networks: 
      - mysql-networks
  
  mysqlsrv:
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: "mysql"
      MYSQL_DATABASE: "testedb"
    ports:
      - "3306:3306"
    volumes: 
      - /home/lukarmar/Desktop/docker/database/mysql:/var/lib/mysql
    networks: 
      - mysql-networks
  
  adminer:
    image: adminer
    ports: 
      - 8080:8080
    networks: 
      - mysql-networks
  
networks: 
  mysql-networks:
    driver: bridge